from __future__ import annotations

from html import escape

from src.automl import AutoMLResult


def build_html_report(result: AutoMLResult) -> str:
    leaderboard_html = result.leaderboard.to_html(index=False, classes="table")
    feature_html = (
        result.feature_importance.to_html(index=False, classes="table")
        if result.feature_importance is not None and not result.feature_importance.empty
        else "<p>The best model does not expose direct feature importance.</p>"
    )
    return f"""
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Bank Customer Churn Risk Report</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 32px; color: #172026; }}
    h1, h2 {{ color: #12355b; }}
    .summary {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }}
    .box {{ border: 1px solid #d5dde5; border-radius: 6px; padding: 12px; background: #f8fafc; }}
    .table {{ border-collapse: collapse; width: 100%; margin: 12px 0 24px; }}
    .table th, .table td {{ border: 1px solid #d5dde5; padding: 8px; text-align: left; }}
    .table th {{ background: #eef4f8; }}
  </style>
</head>
<body>
  <h1>Bank Customer Churn Risk Report</h1>
  <p>This report was generated by a predictive modeling and risk scoring pipeline.</p>

  <div class="summary">
    <div class="box"><strong>Problem Type</strong><br>{escape(result.problem_type.title())}</div>
    <div class="box"><strong>Target</strong><br>{escape(result.target_column)}</div>
    <div class="box"><strong>Best Model</strong><br>{escape(result.best_model_name)}</div>
    <div class="box"><strong>Best Score</strong><br>{result.best_score:.4f}</div>
  </div>

  <h2>Model Leaderboard</h2>
  {leaderboard_html}

  <h2>Feature Importance</h2>
  {feature_html}

  <h2>Conclusion</h2>
  <p>The pipeline completed data preprocessing, churn model training, model evaluation, best-model selection, and explainability steps. The output can help banks prioritize high-risk customers for retention campaigns.</p>
</body>
</html>
"""


def build_notebook_code(target_column: str) -> str:
    return f'''# Bank Customer Churn Risk Scoring Notebook Starter
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import accuracy_score, f1_score

df = pd.read_csv("/kaggle/input/your-dataset/data.csv")
target_column = "{target_column}"

X = df.drop(columns=[target_column])
y = df[target_column]

numeric_features = X.select_dtypes(include=["number", "bool"]).columns.tolist()
categorical_features = X.select_dtypes(exclude=["number", "bool"]).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ]), numeric_features),
        ("categorical", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder(handle_unknown="ignore"))
        ]), categorical_features),
    ]
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(n_estimators=150, random_state=42))
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)
model.fit(X_train, y_train)
predictions = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, predictions))
print("F1 Score:", f1_score(y_test, predictions, average="weighted"))
'''
